// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackingFolder.API.AppContext;

#nullable disable

namespace TrackingFolder.API.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250818094940_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("goldexpertapi")
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrackingFolder.API.Models.GExMeasureResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Ag")
                        .HasColumnType("float");

                    b.Property<double>("AgPlusMinus")
                        .HasColumnType("float");

                    b.Property<double>("Au")
                        .HasColumnType("float");

                    b.Property<double>("AuPlusMinus")
                        .HasColumnType("float");

                    b.Property<double>("Cu")
                        .HasColumnType("float");

                    b.Property<double>("CuPlusMinus")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DeletedOn")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("ElapsedTimeTotal")
                        .HasColumnType("time");

                    b.Property<Guid>("GExMachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GoldExpertMachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("LiveTimeTotal")
                        .HasColumnType("time");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedOn")
                        .HasColumnType("bigint");

                    b.Property<double>("Ni")
                        .HasColumnType("float");

                    b.Property<double>("NiPlusMinus")
                        .HasColumnType("float");

                    b.Property<bool>("PassFail")
                        .HasColumnType("bit");

                    b.Property<double>("Reading")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<double>("Zn")
                        .HasColumnType("float");

                    b.Property<double>("ZnPlusMinus")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("GoldExpertMachineId");

                    b.ToTable("GExMeasureResult", "goldexpertapi");
                });

            modelBuilder.Entity("TrackingFolder.API.Models.GoldExpertMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DeletedOn")
                        .HasColumnType("bigint");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ModifiedOn")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("GoldExpertMachines", "goldexpertapi");

                    b.HasData(
                        new
                        {
                            Id = new Guid("041b6cde-53e1-4a8b-ab62-6c82a763aac7"),
                            FolderPath = "/path/to/machine1",
                            IsDeleted = false,
                            Model = "ModelX",
                            ModifiedBy = "system",
                            ModifiedOn = 1755510579L,
                            Name = "Gold Expert Machine 1",
                            SerialNumber = "SN123456",
                            Version = "1.0"
                        },
                        new
                        {
                            Id = new Guid("bc4cc609-7772-45ed-bd82-35559f8916e5"),
                            FolderPath = "/path/to/machine2",
                            IsDeleted = false,
                            Model = "ModelY",
                            ModifiedBy = "system",
                            ModifiedOn = 1755510579L,
                            Name = "Gold Expert Machine 2",
                            SerialNumber = "SN654321",
                            Version = "1.0"
                        });
                });

            modelBuilder.Entity("TrackingFolder.API.Models.GExMeasureResult", b =>
                {
                    b.HasOne("TrackingFolder.API.Models.GoldExpertMachine", null)
                        .WithMany("GXMeasureResults")
                        .HasForeignKey("GoldExpertMachineId");
                });

            modelBuilder.Entity("TrackingFolder.API.Models.GoldExpertMachine", b =>
                {
                    b.Navigation("GXMeasureResults");
                });
#pragma warning restore 612, 618
        }
    }
}
